In [1]:
import torch

In [2]:
randint = torch.randint(-100,100,(6,)) # random no into 100
randint

tensor([-34,  -2,  55, -45,  66,  66])

In [5]:
tensor = torch.tensor([[0.1,0.2],[2.2, 3.2],[4.9,5.2]])
tensor

tensor([[0.1000, 0.2000],
        [2.2000, 3.2000],
        [4.9000, 5.2000]])

In [6]:
zeros = torch.zeros(2,3) # floating point
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
input = torch.empty(2,3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
arange = torch.arange(5)
arange


tensor([0, 1, 2, 3, 4])

In [11]:
linspace = torch.linspace(3,10,steps = 5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [12]:
logspace = torch.logspace(start= -10,end = 10, steps = 5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [14]:
eye = torch.eye(5) # diagonal
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [16]:
a = torch.empty((2,3), dtype = torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[3214959188336,             0,             0],
        [            0,             0,             0]])

Switch cuda

In [20]:
import torch
import numpy as np
import time

device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

## CPU vs GPU perform in pytorch

In [23]:
start_time = time.time()

zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.4f}")

0.0000


In [25]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100,100,100,100)


start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time 
print(f"{elapsed_time:.8f}")

0.00000000
0.18030071


C:\Users\atcha\AppData\Local\Temp\ipykernel_12688\987370281.py:18: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  rand = np.multiply(np_rand1, np_rand2)


## Embedding Vectors

In [28]:
import torch
import torch.nn as nn

embedding = nn.Embedding(num_embeddings=10, embedding_dim=3)  # 10 words/items, each represented by a 3D vector

input_ids = torch.tensor([1, 5, 7])  # Example indices
embedded_vectors = embedding(input_ids)  # Get embeddings

print(embedded_vectors)


tensor([[ 1.3218,  2.8016,  0.3326],
        [-0.3094, -0.1076, -0.1519],
        [-0.4671,  0.5271, -1.2137]], grad_fn=<EmbeddingBackward0>)
